

export default {

  // 取得目前所有清單資料
  GET_LISTS_DATA: "GET_LISTS_DATA",
  SET_LISTS_DATA: "SET_LISTS_DATA",

  // 讀取 localStorage 的資料到 Store 裡面
  SET_LIST_DATA_FROM_LOCALSTORAGE: "SET_LIST_DATA_FROM_LOCALSTORAGE",
  SET_LIST_DATA_FROM_BACKEND: "SET_LIST_DATA_FROM_BACKEND",

  // 設定/取得要加入清單的資料，讓在 SelectedItem.vue 可以處理資料
  GET_SELECTED_ITEM_DATA: "GET_SELECTED_ITEM_DATA",
  SET_SELECTED_ITEM_DATA: "SET_SELECTED_ITEM_DATA",

  // 在 PopupLists.vue 中將物件資料新增到Store
  ADD_NEW_ITEM_TO_LIST: "ADD_NEW_ITEM_TO_LIST",
  UPDATE_ITEM_IN_LIST: "UPDATE_ITEM_IN_LIST",

  DELETE_ITEM_FROM_LIST: "DELETE_ITEM_FROM_LIST",

  GET_DATA_OF_SELECTED_LIST: "GET_DATA_OF_SELECTED_LIST",
  SET_DATA_IN_SELECTED_LIST: "SET_DATA_IN_SELECTED_LIST",

  GET_SELECTED_LIST_OBJECT: "GET_SELECTED_LIST_OBJECT",


  // 在 CurrentListsType.vue 中設定目前要新增的資料屬於哪一種list type
  GET_SELECTED_LIST_TYPE: "GET_SELECTED_LIST_TYPE",
  SET_SELECTED_LIST_TYPE: "SET_SELECTED_LIST_TYPE",

  GET_LISTS_OF_SELECTED_LIST_TYPE: "GET_LISTS_OF_SELECTED_LIST_TYPE",

  // 在 SelectedItem.vue 中設定，目前要新增的資料屬於哪一種 item type
  GET_SELECTED_ITEM_TYPE: "GET_SELECTED_ITEM_TYPE",
  SET_SELECTED_ITEM_TYPE: "SET_SELECTED_ITEM_TYPE",

  // 在 CurrentListsType.vue 中取得目前已經建立的list資料，作為顯示list選單的內容
  GET_CREATED_LISTS: "GET_CREATED_LISTS",
  CREATE_NEW_LIST: "CREATE_NEW_LIST",
  REORDER_LISTS: "REORDER_LISTS",
  REMOVE_CURRENT_LIST: "REMOVE_CURRENT_LIST",
  UPDATE_LIST_NAME: "UPDATE_LIST_NAME",


  // 在 CurrentLists.vue 中取得資料，用以顯示目前選取的是哪一個清單，並用於
  GET_SELECTED_LIST: "GET_SELECTED_LIST",
  // 在 CurrentLists.vue 中設定目前選取的清單是哪一個，且將清單資訊 emit到父組件， (payload 格式: 類型.清單index，例如 collection.0)
  SET_SELECTED_LIST: "SET_SELECTED_LIST",


  GET_LISTS_SORTING_OPTION: "GET_LISTS_SORTING_OPTION",
  SET_LISTS_SORTING_OPTION: "SET_LISTS_SORTING_OPTION",


  SET_FLAG_IF_DATA_IS_UPDATED: "SET_FLAG_IF_DATA_IS_UPDATED",
  GET_FLAG_IF_DATA_IS_UPDATED: "GET_FLAG_IF_DATA_IS_UPDATED",

  SET_FLAG_IF_DATA_IS_UPLOADED: "SET_FLAG_IF_DATA_IS_UPLOADED",
  GET_FLAG_IF_DATA_IS_UPLOADED: "GET_FLAG_IF_DATA_IS_UPLOADED",

  // ACTION專用: 同時 SET_FLAG_IF_DATA_IS_UPDATED 設為 FALSE 和把 SET_FLAG_IF_DATA_IS_UPLOADED 設為 TRUE
  SET_LIST_IS_UPLOADED_AND_NOT_UPDATED: "SET_LIST_IS_UPLOADED_AND_NOT_UPDATED",

};

