
export default {
  SET_NAME: "SET_NAME",
  GET_NAME: "GET_NAME",

  IS_BEING_AUTHENTICATED: "IS_BEING_AUTHENTICATED",

  SET_IF_AUTHENTICATED: "SET_IF_AUTHENTICATED",
  GET_IF_AUTHENTICATED: "GET_IF_AUTHENTICATED",

  SET_AUTHENTICATION_VALID: "SET_AUTHENTICATION_VALID",
  GET_AUTHENTICATION_VALID: "GET_AUTHENTICATION_VALID",

  SET_DATA_OF_CURRENT_USER: "SET_DATA_OF_CURRENT_USER",
  GET_DATA_OF_CURRENT_USER: "GET_DATA_OF_CURRENT_USER",

  SET_ITEM_LISTS: "SET_ITEM_LISTS",
  GET_ITEM_LISTS: "GET_ITEM_LISTS",

  GET_CURRENT_USER_DATA_WITH_COOKIE: "GET_CURRENT_USER_DATA_WITH_COOKIE"
};

