
export default {
  SET_DISPLAY_LANGUAGE: "SET_DISPLAY_LANGUAGE",
  GET_CURRENT_LANGUAGE: "GET_CURRENT_LANGUAGE",
  GET_CURRENT_LANGUAGE_OPTIONS: "GET_CURRENT_LANGUAGE_OPTIONS",

  SET_TRANSLATION_DATA: "SET_TRANSLATION_DATA",

  GET_TRANSLATION_DATA_BY_ID: "GET_TRANSLATION_DATA_BY_ID",
  SET_TRANSLATION_DATA_BY_ID: "SET_TRANSLATION_DATA_BY_ID",

  GET_TRANSLATION_DATA_BY_NAME: "GET_TRANSLATION_DATA_BY_NAME",
  SET_TRANSLATION_DATA_BY_NAME: "SET_TRANSLATION_DATA_BY_NAME",

  SET_TRANSLATION_DATA_FOR_CREATURES: "SET_TRANSLATION_DATA_FOR_CREATURES",
  GET_TRANSLATION_DATA_FOR_CREATURES: "GET_TRANSLATION_DATA_FOR_CREATURES",

  GET_TRANSLATION_DATA_FOR_RECIPES: "GET_TRANSLATION_DATA_FOR_RECIPES",
  SET_TRANSLATION_DATA_FOR_RECIPES: "SET_TRANSLATION_DATA_FOR_RECIPES"



};

