



export default {
  // 從API取得並設定資料
  FETCH_TRANSLATED_ITEM_DATA: "FETCH_TRANSLATED_ITEM_DATA",
  SET_FETCHED_ITEM_DATA: "SET_FETCHED_ITEM_DATA",


  // 設定/取得查詢結果的資料
  SET_ITEMS_FOR_QUERY: "SET_ITEMS_FOR_QUERY",
  GET_ITEMS_FOR_QUERY: "GET_ITEMS_FOR_QUERY",

  // 依照篩選條件更新 查詢結果的資料
  RECALCULATE_ITEMS_FOR_QUERY: "RECALCULATE_ITEMS_FOR_QUERY",

  // 設定/取得 查詢類別的內容 (做為顯示選單內容的資料)
  SET_ITEM_CATEGORIES: "SET_ITEM_CATEGORIES",
  GET_ITEM_CATEGORIES: "get_ITEM_CATEGORIES",

  // 設定/取得 目前選取的 "分類" 查詢關鍵字 (作為篩選資料的選項)
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  GET_SELECTED_CATEGORY: "get_SELECTED_CATEGORY",

  // 設定/取得 目前選取的 "排序" 查詢關鍵字 (作為篩選資料的選項)
  get_SELECTED_SORTING_OPTION: "get_SELECTED_SORTING_OPTION",
  SET_SELECTED_SORTING_OPTION: "SET_SELECTED_SORTING_OPTION",

  // 設定/取得 目前選取的 "排序" 查詢關鍵字 (作為篩選資料的選項)
  get_SELECTED_SORTING_OPTION: "get_SELECTED_SORTING_OPTION",
  SET_SELECTED_SORTING_OPTION: "SET_SELECTED_SORTING_OPTION",

  // 設定/取得 目前選取的 "排序" 查詢關鍵字 (作為篩選資料的選項)
  get_QUERY_KEYWORD: "get_QUERY_KEYWORD",
  SET_QUERY_KEYWORD: "SET_QUERY_KEYWORD",

  // ======================================================


  // 1) 從API取得並設定資料
  FETCH_ITEM_DETAILS_DATA: "FETCH_ITEM_DETAILS_DATA",
  SET_FETCHED_ITEM_DETAILS_DATA: "SET_FETCHED_ITEM_DETAILS_DATA",

  // 2) 設定/取得查詢結果的分類
  SET_ITEM_DETAILS_CATEGORIES: "SET_ITEM_DETAILS_CATEGORIES",
  get_ITEM_DETAILS_CATEGORIES: "get_ITEM_DETAILS_CATEGORIES",


  // 3) 設定/取得查詢結果的資料
  SET_CURRENT_ITEM_CATEGORY: "SET_CURRENT_ITEM_CATEGORY",
  get_CURRENT_ITEM_CATEGORY: "get_CURRENT_ITEM_CATEGORY",


  // 4) 設定/取得TAG
  SET_CURRENT_ITEM_TAGS: "SET_CURRENT_ITEM_TAGS",
  get_CURRENT_ITEM_TAGS: "get_CURRENT_ITEM_TAGS",

  // 5) 篩選要顯示的資料
  SET_FILTERED_ITEMS: "SET_FILTERED_ITEMS",
  get_FILTERED_ITEMS: "get_FILTERED_ITEMS",



};

