

// export const FETCH_ITEMS_FROM_API = "FETCH_ITEMS_FROM_API";
// export const GET_ITEMS_FOR_QUERY = "GET_ITEMS_FOR_QUERY";

// export const SET_ITEM_CATEGORIES = "SET_ITEM_CATEGORIES";
// export const GET_ITEM_CATEGORIES = "GET_ITEM_CATEGORIES";


export default {
  GET_NAVBAR_STATUS: "GET_NAVBAR_STATUS",
  SET_NAVBAR_STATUS: "SET_NAVBAR_STATUS",

  GET_LIST_POPUP_STATUS: "GET_LIST_POPUP_STATUS",
  SET_LIST_POPUP_STATUS: "SET_LIST_POPUP_STATUS",

  GET_LIST_POPUP_DATA: "GET_LIST_POPUP_DATA",
  SET_LIST_POPUP_DATA: "SET_LIST_POPUP_DATA",

};

